services:
  - docker

script:
  # Build images
  - echo '------BUILDING IMAGES------'
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t udagram-api-user:v1 ./udagram-api-user
  - docker build -t udagram-frontend:v1 ./udagram-frontend
  - docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy

  # Tagging images
  - echo '------TAGGING IMAGES------'
  - docker tag udagram-api-feed:v1 huytran1996/udagram-api-feed:v1
  - docker tag udagram-api-user:v1 huytran1996/udagram-api-user:v1
  - docker tag udagram-frontend:v1 huytran1996/udagram-frontend:v1
  - docker tag udagram-reverseproxy:v1 huytran1996/udagram-reverseproxy:v1

  - echo '------LISTING IMAGES------'
  - docker image ls
after_success:
  # Login to dockerhub and push images
  - echo '------LOGGING IN TO DOCKER------'
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo '------PUSHING IMAGES------'
  - docker push huytran1996/udagram-api-feed:v1
  - docker push huytran1996/udagram-api-user:v1
  - docker push huytran1996/udagram-frontend:v1
  - docker push huytran1996/reverseproxy:v1